- name: Configure systemd-networkd and nftables
  hosts: raspberry_pi
  become: yes
  tasks:
    # Ensure systemd-networkd is installed and enabled
    - name: Ensure systemd-networkd is enabled
      systemd:
        name: systemd-networkd
        enabled: yes
        state: started

    # Configure static IP for wlan1
    - name: Set up wlan1 network configuration
      copy:
        dest: /etc/systemd/network/10-wlan1.network
        content: |
          [Match]
          Name=wlan1

          [Network]
          Address=192.168.4.1/24
          DHCPServer=yes
      notify: Restart systemd-networkd

    # Install nftables
    - name: Install nftables
      apt:
        name: nftables
        state: present

    # Enable and start nftables service
    - name: Enable and start nftables service
      systemd:
        name: nftables
        enabled: yes
        state: started

    # Deploy nftables configuration
    - name: Deploy nftables configuration
      copy:
        dest: /etc/nftables.conf
        content: |
          table inet nat {
              chain postrouting {
                  type nat hook postrouting priority 100; policy accept;
                  oifname "eth0" masquerade
              }
          }

          table inet filter {
              chain forward {
                  type filter hook forward priority 0; policy drop;
                  iifname "wlan1" oifname "eth0" accept
                  iifname "eth0" oifname "wlan1" accept
              }
          }
      notify: Restart nftables

  handlers:
    # Handler to restart systemd-networkd
    - name: Restart systemd-networkd
      systemd:
        name: systemd-networkd
        state: restarted

    # Handler to restart nftables
    - name: Restart nftables
      systemd:
        name: nftables
        state: restarted

