---
- name: Configure Raspberry Pi as WiFi Hotspot with USB Dongle
  hosts: all
  become: yes
  vars:
    home_wifi_ssid: "{{ lookup('env', 'HOME_WIFI_SSID') }}"
    home_wifi_password: "{{ lookup('env', 'HOME_WIFI_PASSWORD') }}"
    hotspot_ssid: "PiHotspot"
    hotspot_password: "HotspotPassword"

  tasks:
    - name: Install required packages
      apt:
        name:
          - hostapd
          - dnsmasq
        state: present

    - name: Configure wpa_supplicant for home WiFi on wlan0
      copy:
        dest: /etc/wpa_supplicant/wpa_supplicant.conf
        content: |
          country=US
          ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
          update_config=1

          network={
              ssid="{{ home_wifi_ssid }}"
              psk="{{ home_wifi_password }}"
              key_mgmt=WPA-PSK
          }
      notify: Restart networking

    - name: Configure DHCP for wlan1 (hotspot)
      copy:
        dest: /etc/dnsmasq.conf
        content: |
          interface=wlan1
          dhcp-range=192.168.50.10,192.168.50.100,255.255.255.0,24h
      notify: Restart dnsmasq

    - name: Configure hostapd for hotspot
      copy:
        dest: /etc/hostapd/hostapd.conf
        content: |
          interface=wlan1
          ssid={{ hotspot_ssid }}
          hw_mode=g
          channel=7
          wmm_enabled=0
          macaddr_acl=0
          auth_algs=1
          ignore_broadcast_ssid=0
          wpa=2
          wpa_passphrase={{ hotspot_password }}
          wpa_key_mgmt=WPA-PSK
          rsn_pairwise=CCMP
      notify: Restart hostapd

    - name: Enable IP forwarding
      lineinfile:
        path: /etc/sysctl.conf
        line: 'net.ipv4.ip_forward=1'
        state: present
      notify: Apply sysctl changes

    - name: Configure NAT routing
      blockinfile:
        path: /etc/rc.local
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        content: |
          iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
          iptables -A FORWARD -i wlan0 -o wlan1 -m state --state RELATED,ESTABLISHED -j ACCEPT
          iptables -A FORWARD -i wlan1 -o wlan0 -j ACCEPT
      notify: Apply iptables rules

  handlers:
    - name: Restart networking
      systemd:
        name: networking
        state: restarted

    - name: Restart dnsmasq
      systemd:
        name: dnsmasq
        state: restarted

    - name: Restart hostapd
      systemd:
        name: hostapd
        state: restarted

    - name: Apply sysctl changes
      command: sysctl -p

    - name: Apply iptables rules
      command: iptables-save > /etc/iptables.rules

