---
- name: Configure Raspberry Pi as WiFi Hotspot with USB Dongle
  hosts: localhost
  become: yes
#  vars_prompt:
#    - name: home_ssid
#      prompt: "Enter your home WiFi SSID"
#      private: no
#    - name: home_psk
#      prompt: "Enter your home WiFi Password"
#      private: yes
#    - name: hotspot_ssid
#      prompt: "Enter your Hotspot SSID"
#      private: no
#    - name: hotspot_psk
#      prompt: "Enter your Hotspot Password"
#      private: yes

  tasks:
    - name: Install required packages
      apt:
        name:
          - hostapd
          - dnsmasq
          - iptables
          - rfkill
        state: present

    - name: Unmask hostapd
      command: systemctl unmask hostapd

    - name: Configure DHCP for hotspot
      copy:
        dest: /etc/dnsmasq.conf
        content: |
          interface=wlan1
          dhcp-range=192.168.4.2,192.168.4.20,255.255.255.0,24h
      notify: Restart dnsmasq

    - name: Configure hostapd for hotspot
      copy:
        dest: /etc/hostapd/hostapd.conf
        content: |
          interface=wlan1
          ssid=pihotspot
          hw_mode=g
          channel=7
          wmm_enabled=0
          macaddr_acl=0
          auth_algs=1
          ignore_broadcast_ssid=0
          wpa=2
          #wpa_passphrase={{ hotspot_psk }}
          wpa_passphrase="hotspot"
          wpa_key_mgmt=WPA-PSK
          rsn_pairwise=CCMP
      notify: Restart hostapd

    - name: Set systemd service for hostapd
      lineinfile:
        path: /etc/default/hostapd
        regexp: '^DAEMON_CONF='
        line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
      notify: Restart hostapd

    - name: Configure NAT routing
      copy:
        dest: /etc/systemd/system/nat-routing.service
        content: |
          [Unit]
          Description=Enable NAT Routing
          After=network.target

          [Service]
          Type=oneshot
          ExecStart=/sbin/iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
          RemainAfterExit=true

          [Install]
          WantedBy=multi-user.target
      notify: Reload systemd

    - name: Enable NAT routing service
      systemd:
        name: nat-routing
        enabled: yes
        state: started

  handlers:
    - name: Restart dnsmasq
      service:
        name: dnsmasq
        state: restarted

    - name: Restart hostapd
      service:
        name: hostapd
        state: restarted

    - name: Reload systemd
      command: systemctl daemon-reload

